import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How BetterPomo collects, uses, and protects your data.",
  alternates: { canonical: "/privacy" },
};

const CONTACT_EMAIL = "lucianomenezes655@gmail.com";

export default function PrivacyPage() {
  return (
    <>
      <h1>Privacy Policy</h1>
      <p>Last updated: July 9, 2026</p>

      <p>
        BetterPomo (&ldquo;we&rdquo;, &ldquo;us&rdquo;) is a shared Pomodoro and focus-timer app.
        This policy explains what data we collect, why we collect it, and what control you have
        over it. The short version: we collect only what the app needs to work, we show no ads,
        and we never sell your data.
      </p>

      <h2>What we collect</h2>
      <ul>
        <li>
          <strong>Account data.</strong> When you sign up we store your email address and, if you
          use Google or Apple sign-in, the basic account identifier the provider shares with us.
          Authentication is handled by Supabase.
        </li>
        <li>
          <strong>Profile data.</strong> Your username, chosen emoji, optional bio, and privacy
          setting. Your username and profile are visible to other users unless you set your
          profile to private.
        </li>
        <li>
          <strong>Session history.</strong> When you complete a focus session, we save its name,
          duration, timers used, participants, and any tasks you attached, so you can see your
          stats and history.
        </li>
        <li>
          <strong>Social data.</strong> Friend connections, friend requests, and notifications
          generated by activity in the app.
        </li>
        <li>
          <strong>Messages.</strong> Direct messages and session chat are stored so they can be
          delivered. Direct messages are automatically deleted 24 hours after they are sent.
        </li>
        <li>
          <strong>Product analytics.</strong> On the web app we may collect anonymous usage
          events (for example, that a session was created) through PostHog to understand which
          features are used and improve the product. These events are tied to your account id,
          are never shared with advertisers, and are not collected by the mobile apps.
        </li>
      </ul>

      <h2>What we don&rsquo;t do</h2>
      <ul>
        <li>We do not show ads and do not use advertising or cross-site tracking scripts.</li>
        <li>We do not sell, rent, or share your personal data with third parties for marketing.</li>
        <li>We do not collect data unrelated to running the app.</li>
      </ul>

      <h2>How your data is used</h2>
      <p>
        Your data is used solely to provide BetterPomo&rsquo;s features: signing you in, running
        shared timer sessions, showing your history and stats, connecting you with friends, and
        delivering messages and notifications.
      </p>

      <h2>Where your data lives</h2>
      <p>
        Data is stored with Supabase, our database and authentication provider. Connections to
        the service are encrypted with HTTPS. Access to your data through the app is controlled
        by authentication tokens tied to your account.
      </p>

      <h2>Data retention and deletion</h2>
      <p>
        Direct messages are deleted automatically after 24 hours. Abandoned live sessions are
        cleaned up automatically. Your account data, profile, and session history are kept until
        you delete your account. You can permanently delete your account and all associated data
        yourself at any time from <strong>Settings &rarr; Delete account</strong> in the web app
        (app.betterpomo.com) or in the iOS/Android app. You can also request deletion by
        contacting us at the email below.
      </p>

      <h2>Cookies</h2>
      <p>
        We use the cookies required to keep you signed in (Supabase authentication session
        cookies) and, on the web app, local storage used by our first-party product analytics.
        There are no advertising cookies.
      </p>

      <h2>Children</h2>
      <p>
        BetterPomo is not directed at children under 13, and we do not knowingly collect data
        from them.
      </p>

      <h2>Changes to this policy</h2>
      <p>
        If we make material changes to this policy, we will update this page and the date above.
      </p>

      <h2>Contact</h2>
      <p>
        Questions or data requests: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
      </p>
    </>
  );
}
